use crate::models::{Location, PartnerWithLocations, Product};
use chrono::Utc;
use rand::Rng;
use std::time::Duration;

/// Simulates fetching partners from an external service
pub async fn fetch_partners() -> Vec<PartnerWithLocations> {
    // Simulate network delay (200-800ms)
    let delay = rand::thread_rng().gen_range(200..800);
    tokio::time::sleep(Duration::from_millis(delay)).await;

    let now = Utc::now().to_rfc3339();

    vec![
        PartnerWithLocations {
            id: "p1".to_string(),
            name: "Acme Corporation SRL".to_string(),
            cif: Some("12345678".to_string()),
            reg_com: Some("J40/123456/2020".to_string()),
            cod: Some("ACME001".to_string()),
            blocat: Some("NU".to_string()),
            tva_la_incasare: Some("NU".to_string()),
            persoana_fizica: Some("NU".to_string()),
            cod_extern: None,
            cod_intern: Some("INT001".to_string()),
            observatii: Some("Client principal".to_string()),
            data_adaugarii: None,
            clasa: None,
            simbol_clasa: None,
            cod_clasa: None,
            inactiv: Some("NU".to_string()),
            categorie_pret_implicita: None,
            simbol_categorie_pret: None,
            scadenta_la_vanzare: None,
            scadenta_la_cumparare: None,
            credit_client: None,
            discount_fix: None,
            tip_partener: None,
            mod_aplicare_discount: None,
            moneda: None,
            data_nastere: None,
            caracterizare_contabila_denumire: None,
            caracterizare_contabila_simbol: None,
            created_at: now.clone(),
            updated_at: now.clone(),
            locations: vec![
                Location {
                    id: "l1".to_string(),
                    partner_id: "p1".to_string(),
                    name: "Sediu Central București".to_string(),
                    address: Some("Str. Victoriei 100, Sector 1".to_string()),
                    cod_sediu: Some("SED001".to_string()),
                    localitate: Some("București".to_string()),
                    strada: Some("Victoriei".to_string()),
                    numar: Some("100".to_string()),
                    judet: Some("București".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("010101".to_string()),
                    telefon: Some("021-123-4567".to_string()),
                    email: Some("contact@acme.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
                Location {
                    id: "l2".to_string(),
                    partner_id: "p1".to_string(),
                    name: "Sucursala Cluj".to_string(),
                    address: Some("Str. Napoca 25, Cluj-Napoca".to_string()),
                    cod_sediu: Some("SED002".to_string()),
                    localitate: Some("Cluj-Napoca".to_string()),
                    strada: Some("Napoca".to_string()),
                    numar: Some("25".to_string()),
                    judet: Some("Cluj".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("400001".to_string()),
                    telefon: Some("0264-123-456".to_string()),
                    email: Some("cluj@acme.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
            ],
        },
        PartnerWithLocations {
            id: "p2".to_string(),
            name: "TechStart Solutions SRL".to_string(),
            cif: Some("87654321".to_string()),
            reg_com: Some("J40/654321/2021".to_string()),
            cod: Some("TECH001".to_string()),
            blocat: Some("NU".to_string()),
            tva_la_incasare: Some("NU".to_string()),
            persoana_fizica: Some("NU".to_string()),
            cod_extern: None,
            cod_intern: Some("INT002".to_string()),
            observatii: None,
            data_adaugarii: None,
            clasa: None,
            simbol_clasa: None,
            cod_clasa: None,
            inactiv: Some("NU".to_string()),
            categorie_pret_implicita: None,
            simbol_categorie_pret: None,
            scadenta_la_vanzare: None,
            scadenta_la_cumparare: None,
            credit_client: None,
            discount_fix: None,
            tip_partener: None,
            mod_aplicare_discount: None,
            moneda: None,
            data_nastere: None,
            caracterizare_contabila_denumire: None,
            caracterizare_contabila_simbol: None,
            created_at: now.clone(),
            updated_at: now.clone(),
            locations: vec![Location {
                id: "l3".to_string(),
                partner_id: "p2".to_string(),
                name: "Birou Principal".to_string(),
                address: Some("Bd. Unirii 50, București".to_string()),
                cod_sediu: Some("SED003".to_string()),
                localitate: Some("București".to_string()),
                strada: Some("Unirii".to_string()),
                numar: Some("50".to_string()),
                judet: Some("București".to_string()),
                tara: Some("România".to_string()),
                cod_postal: Some("030101".to_string()),
                telefon: Some("021-234-5678".to_string()),
                email: Some("office@techstart.ro".to_string()),
                inactiv: Some("NU".to_string()),
            }],
        },
        PartnerWithLocations {
            id: "p3".to_string(),
            name: "Global Trade Import-Export SA".to_string(),
            cif: Some("11223344".to_string()),
            reg_com: Some("J40/223344/2019".to_string()),
            cod: Some("GLOB001".to_string()),
            blocat: Some("NU".to_string()),
            tva_la_incasare: Some("DA".to_string()),
            persoana_fizica: Some("NU".to_string()),
            cod_extern: Some("EXT001".to_string()),
            cod_intern: Some("INT003".to_string()),
            observatii: Some("TVA la încasare".to_string()),
            data_adaugarii: None,
            clasa: None,
            simbol_clasa: None,
            cod_clasa: None,
            inactiv: Some("NU".to_string()),
            categorie_pret_implicita: None,
            simbol_categorie_pret: None,
            scadenta_la_vanzare: None,
            scadenta_la_cumparare: None,
            credit_client: None,
            discount_fix: None,
            tip_partener: None,
            mod_aplicare_discount: None,
            moneda: None,
            data_nastere: None,
            caracterizare_contabila_denumire: None,
            caracterizare_contabila_simbol: None,
            created_at: now.clone(),
            updated_at: now.clone(),
            locations: vec![
                Location {
                    id: "l4".to_string(),
                    partner_id: "p3".to_string(),
                    name: "Depozit Constanța".to_string(),
                    address: Some("Zona Industrială, Constanța".to_string()),
                    cod_sediu: Some("SED004".to_string()),
                    localitate: Some("Constanța".to_string()),
                    strada: Some("Zona Industrială".to_string()),
                    numar: None,
                    judet: Some("Constanța".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("900001".to_string()),
                    telefon: Some("0241-123-456".to_string()),
                    email: Some("depozit@global.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
                Location {
                    id: "l5".to_string(),
                    partner_id: "p3".to_string(),
                    name: "Showroom Timișoara".to_string(),
                    address: Some("Calea Aradului 15, Timișoara".to_string()),
                    cod_sediu: Some("SED005".to_string()),
                    localitate: Some("Timișoara".to_string()),
                    strada: Some("Calea Aradului".to_string()),
                    numar: Some("15".to_string()),
                    judet: Some("Timiș".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("300001".to_string()),
                    telefon: Some("0256-123-456".to_string()),
                    email: Some("showroom@global.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
                Location {
                    id: "l6".to_string(),
                    partner_id: "p3".to_string(),
                    name: "Punct de lucru Iași".to_string(),
                    address: Some("Str. Păcurari 80, Iași".to_string()),
                    cod_sediu: Some("SED006".to_string()),
                    localitate: Some("Iași".to_string()),
                    strada: Some("Păcurari".to_string()),
                    numar: Some("80".to_string()),
                    judet: Some("Iași".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("700001".to_string()),
                    telefon: Some("0232-123-456".to_string()),
                    email: Some("iasi@global.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
            ],
        },
        PartnerWithLocations {
            id: "p4".to_string(),
            name: "Digital Services & Co SRL".to_string(),
            cif: Some("55667788".to_string()),
            reg_com: Some("J40/667788/2022".to_string()),
            cod: Some("DIGI001".to_string()),
            blocat: Some("NU".to_string()),
            tva_la_incasare: Some("NU".to_string()),
            persoana_fizica: Some("NU".to_string()),
            cod_extern: None,
            cod_intern: Some("INT004".to_string()),
            observatii: None,
            data_adaugarii: None,
            clasa: None,
            simbol_clasa: None,
            cod_clasa: None,
            inactiv: Some("NU".to_string()),
            categorie_pret_implicita: None,
            simbol_categorie_pret: None,
            scadenta_la_vanzare: None,
            scadenta_la_cumparare: None,
            credit_client: None,
            discount_fix: None,
            tip_partener: None,
            mod_aplicare_discount: None,
            moneda: None,
            data_nastere: None,
            caracterizare_contabila_denumire: None,
            caracterizare_contabila_simbol: None,
            created_at: now.clone(),
            updated_at: now.clone(),
            locations: vec![Location {
                id: "l7".to_string(),
                partner_id: "p4".to_string(),
                name: "Sediu Brașov".to_string(),
                address: Some("Str. Republicii 35, Brașov".to_string()),
                cod_sediu: Some("SED007".to_string()),
                localitate: Some("Brașov".to_string()),
                strada: Some("Republicii".to_string()),
                numar: Some("35".to_string()),
                judet: Some("Brașov".to_string()),
                tara: Some("România".to_string()),
                cod_postal: Some("500001".to_string()),
                telefon: Some("0268-123-456".to_string()),
                email: Some("brasov@digital.ro".to_string()),
                inactiv: Some("NU".to_string()),
            }],
        },
        PartnerWithLocations {
            id: "p5".to_string(),
            name: "Construct Expert SRL".to_string(),
            cif: Some("99887766".to_string()),
            reg_com: Some("J40/887766/2020".to_string()),
            cod: Some("CONS001".to_string()),
            blocat: Some("NU".to_string()),
            tva_la_incasare: Some("NU".to_string()),
            persoana_fizica: Some("NU".to_string()),
            cod_extern: None,
            cod_intern: Some("INT005".to_string()),
            observatii: Some("Firma de constructii".to_string()),
            data_adaugarii: None,
            clasa: None,
            simbol_clasa: None,
            cod_clasa: None,
            inactiv: Some("NU".to_string()),
            categorie_pret_implicita: None,
            simbol_categorie_pret: None,
            scadenta_la_vanzare: None,
            scadenta_la_cumparare: None,
            credit_client: None,
            discount_fix: None,
            tip_partener: None,
            mod_aplicare_discount: None,
            moneda: None,
            data_nastere: None,
            caracterizare_contabila_denumire: None,
            caracterizare_contabila_simbol: None,
            created_at: now.clone(),
            updated_at: now.clone(),
            locations: vec![
                Location {
                    id: "l8".to_string(),
                    partner_id: "p5".to_string(),
                    name: "Sediu Central".to_string(),
                    address: Some("Bd. Decebal 10, Oradea".to_string()),
                    cod_sediu: Some("SED008".to_string()),
                    localitate: Some("Oradea".to_string()),
                    strada: Some("Decebal".to_string()),
                    numar: Some("10".to_string()),
                    judet: Some("Bihor".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("410001".to_string()),
                    telefon: Some("0259-123-456".to_string()),
                    email: Some("office@construct.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
                Location {
                    id: "l9".to_string(),
                    partner_id: "p5".to_string(),
                    name: "Depozit Materiale".to_string(),
                    address: Some("Zona Industrială Vest, Oradea".to_string()),
                    cod_sediu: Some("SED009".to_string()),
                    localitate: Some("Oradea".to_string()),
                    strada: Some("Zona Industrială Vest".to_string()),
                    numar: None,
                    judet: Some("Bihor".to_string()),
                    tara: Some("România".to_string()),
                    cod_postal: Some("410002".to_string()),
                    telefon: Some("0259-234-567".to_string()),
                    email: Some("depozit@construct.ro".to_string()),
                    inactiv: Some("NU".to_string()),
                },
            ],
        },
    ]
}

/// Simulates fetching products from an external service
pub async fn fetch_products() -> Vec<Product> {
    // Simulate network delay (200-800ms)
    let delay = rand::thread_rng().gen_range(200..800);
    tokio::time::sleep(Duration::from_millis(delay)).await;

    vec![
        Product {
            id: "pr1".to_string(),
            name: "Laptop Dell XPS 15".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 5500.0,
            class: Some("Electronice".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr2".to_string(),
            name: "Monitor LG 27\" 4K".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 1200.0,
            class: Some("Electronice".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr3".to_string(),
            name: "Cablu USB Type-C 2m".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 35.0,
            class: Some("Accesorii".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr4".to_string(),
            name: "Hârtie A4 (500 coli)".to_string(),
            unit_of_measure: "top".to_string(),
            price: 25.0,
            class: Some("Birou".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr5".to_string(),
            name: "Toner HP 26A".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 350.0,
            class: Some("Birou".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr6".to_string(),
            name: "Tastatură Logitech MX Keys".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 450.0,
            class: Some("Periferice".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr7".to_string(),
            name: "Mouse Logitech MX Master 3".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 380.0,
            class: Some("Periferice".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr8".to_string(),
            name: "SSD Samsung 1TB NVMe".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 420.0,
            class: Some("Componente".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr9".to_string(),
            name: "Webcam Logitech C920".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 320.0,
            class: Some("Periferice".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr10".to_string(),
            name: "Casti Audio-Technica ATH-M50x".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 650.0,
            class: Some("Audio".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr11".to_string(),
            name: "Hub USB-C 7-in-1".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 180.0,
            class: Some("Accesorii".to_string()),
            tva_percent: Some(19.0),
        },
        Product {
            id: "pr12".to_string(),
            name: "Stand Laptop Ajustabil".to_string(),
            unit_of_measure: "buc".to_string(),
            price: 150.0,
            class: Some("Accesorii".to_string()),
            tva_percent: Some(19.0),
        },
    ]
}

/// Simulates sending an invoice to an external service
/// Returns Ok(()) with 50% probability, Err with 50% probability
pub async fn send_invoice_to_external() -> Result<(), String> {
    // Simulate network delay (500-1500ms)
    let delay = rand::thread_rng().gen_range(500..1500);
    tokio::time::sleep(Duration::from_millis(delay)).await;

    // 50% chance of failure
    if rand::random::<bool>() {
        Ok(())
    } else {
        Err("Eroare rețea: Conexiunea a fost refuzată".to_string())
    }
}
